### ISSUE TITLE
please update pip.. curent version has wLightBoxSAPIdevice

### ISSUE THREAD

**Issue by UrbanskiDawid** [zen/python-blebox#2]
>>> from pyblebox.wlightboxs import wLightBoxS
>>> wlightboxs1 = wLightBoxS("192.168.1.116")
>>> wlightboxs1
<pyblebox.wlightboxs.wLightBoxS object at 0xb769186c>
>>> wlightboxs1.get_status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dawid/.local/lib/python3.6/site-packages/pyblebox/wlightboxs.py", line 52, in get_status
    '{}/{}/{}'.format(self.resource, wLightBoxSAPIdevice, 'state'), timeout=self.timeout)
NameError: name 'wLightBoxSAPIdevice' is not defined

**Comment by zen** [comment]
Hi,

I'll take a look at this over the weekend
